version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - ticket-network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: ticket_system
      POSTGRES_USER: rishabh
      POSTGRES_PASSWORD: rishabhsingh@1894
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ticket-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8501:8501"
    env_file:
      - ./frontend/.env.frontend
    depends_on:
      - backend
    networks:
      - ticket-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env.backend
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - ticket-network

  db:
    build:
      context: .
      dockerfile: db/Dockerfile
    env_file:
      - ./db/.env.dbserver
    depends_on:
      - rabbitmq
      - postgres
    networks:
      - ticket-network

volumes:
  postgres_data:

networks:
  ticket-network:
    driver: bridge
